<?php
return array(
    'example' => 4,
    'date' => 1595808000,
    'year' => 2020,
    'month_int' => 7,
    'month_iso' => 'Jul',
    'month_name' => 'July',
    'day' => 27,
    'month_data' =>
    array(
        1 =>
        array(
            'date' => 1,
            'day_of_week' => 'WED',
        ),
        2 =>
        array(
            'date' => 2,
            'day_of_week' => 'THU',
        ),
        3 =>
        array(
            'date' => 3,
            'day_of_week' => 'FRI',
        ),
        4 =>
        array(
            'date' => 4,
            'day_of_week' => 'SAT',
        ),
        5 =>
        array(
            'date' => 5,
            'day_of_week' => 'SUN',
        ),
        6 =>
        array(
            'date' => 6,
            'day_of_week' => 'MON',
        ),
        7 =>
        array(
            'date' => 7,
            'day_of_week' => 'TUE',
        ),
        8 =>
        array(
            'date' => 8,
            'day_of_week' => 'WED',
        ),
        9 =>
        array(
            'date' => 9,
            'day_of_week' => 'THU',
        ),
        10 =>
        array(
            'date' => 10,
            'day_of_week' => 'FRI',
        ),
        11 =>
        array(
            'date' => 11,
            'day_of_week' => 'SAT',
        ),
        12 =>
        array(
            'date' => 12,
            'day_of_week' => 'SUN',
        ),
        13 =>
        array(
            'date' => 13,
            'day_of_week' => 'MON',
        ),
        14 =>
        array(
            'date' => 14,
            'day_of_week' => 'TUE',
        ),
        15 =>
        array(
            'date' => 15,
            'day_of_week' => 'WED',
        ),
        16 =>
        array(
            'date' => 16,
            'day_of_week' => 'THU',
        ),
        17 =>
        array(
            'date' => 17,
            'day_of_week' => 'FRI',
        ),
        18 =>
        array(
            'date' => 18,
            'day_of_week' => 'SAT',
        ),
        19 =>
        array(
            'date' => 19,
            'day_of_week' => 'SUN',
        ),
        20 =>
        array(
            'date' => 20,
            'day_of_week' => 'MON',
        ),
        21 =>
        array(
            'date' => 21,
            'day_of_week' => 'TUE',
        ),
        22 =>
        array(
            'date' => 22,
            'day_of_week' => 'WED',
        ),
        23 =>
        array(
            'date' => 23,
            'day_of_week' => 'THU',
        ),
        24 =>
        array(
            'date' => 24,
            'day_of_week' => 'FRI',
        ),
        25 =>
        array(
            'date' => 25,
            'day_of_week' => 'SAT',
        ),
        26 =>
        array(
            'date' => 26,
            'day_of_week' => 'SUN',
        ),
        27 =>
        array(
            'date' => 27,
            'day_of_week' => 'MON',
        ),
        28 =>
        array(
            'date' => 28,
            'day_of_week' => 'TUE',
        ),
        29 =>
        array(
            'date' => 29,
            'day_of_week' => 'WED',
        ),
        30 =>
        array(
            'date' => 30,
            'day_of_week' => 'THU',
        ),
        31 =>
        array(
            'date' => 31,
            'day_of_week' => 'FRI',
        ),
    ),
    'week' =>
    array(
        27 =>
        array(
            'date' => 27,
            'day_of_week' => 'MON',
        ),
        28 =>
        array(
            'date' => 28,
            'day_of_week' => 'TUE',
        ),
        29 =>
        array(
            'date' => 29,
            'day_of_week' => 'WED',
        ),
        30 =>
        array(
            'date' => 30,
            'day_of_week' => 'THU',
        ),
        31 =>
        array(
            'date' => 31,
            'day_of_week' => 'FRI',
        ),
    ),
    'calendar' =>
    array(
        0 =>
        array(
            0 =>
            array(
                'date' => '2020-06-29',
                'day' => 29,
                'day_of_week' => 'MON',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '91',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593435600',
                        'home_goals' => '3',
                        'guest_goals' => '3',
                        'time' => '1593435600',
                        'date' => '2020-06-29',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=91',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 3 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '613',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '6',
                        'gast_verein' => '5',
                        'datum' => '1593453600',
                        'home_tore' => '7',
                        'gast_tore' => '1',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => 'FC Bayern München',
                        'guest_team_short' => 'FCB',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=613',
                        'color_code' => 'red',
                        'c_heading' => 'SCF vs. FCB 7 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    2 =>
                    array(
                        'id' => '614',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '11',
                        'gast_verein' => '18',
                        'datum' => '1593453600',
                        'home_tore' => '2',
                        'gast_tore' => '1',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'FC Augsburg',
                        'home_team_short' => 'FCA',
                        'guest_team_name' => 'SC Paderborn 07',
                        'guest_team_short' => 'SCP',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=614',
                        'color_code' => 'red',
                        'c_heading' => 'FCA vs. SCP 2 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    3 =>
                    array(
                        'id' => '615',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '9',
                        'gast_verein' => '15',
                        'datum' => '1593453600',
                        'home_tore' => '4',
                        'gast_tore' => '2',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'TSG 1899 Hoffenheim',
                        'home_team_short' => 'TSG',
                        'guest_team_name' => 'Werder Bremen',
                        'guest_team_short' => 'SVW',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=615',
                        'color_code' => 'red',
                        'c_heading' => 'TSG vs. SVW 4 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    4 =>
                    array(
                        'id' => '616',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '2',
                        'gast_verein' => '17',
                        'datum' => '1593453600',
                        'home_tore' => '6',
                        'gast_tore' => '8',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Hamburger SV',
                        'home_team_short' => 'HSV',
                        'guest_team_name' => '1.FC Köln',
                        'guest_team_short' => 'KLN',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=616',
                        'color_code' => 'red',
                        'c_heading' => 'HSV vs. KLN 6 - 8',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    5 =>
                    array(
                        'id' => '617',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '4',
                        'gast_verein' => '16',
                        'datum' => '1593453600',
                        'home_tore' => '5',
                        'gast_tore' => '4',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'FC Schalke 04',
                        'home_team_short' => 'S04',
                        'guest_team_name' => 'Fortuna Düsseldorf',
                        'guest_team_short' => 'F95',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=617',
                        'color_code' => 'red',
                        'c_heading' => 'S04 vs. F95 5 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    6 =>
                    array(
                        'id' => '618',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '3',
                        'gast_verein' => '1',
                        'datum' => '1593453600',
                        'home_tore' => '4',
                        'gast_tore' => '9',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Bor. Mönchengladbach',
                        'home_team_short' => 'BMG',
                        'guest_team_name' => 'Borussia Dortmund',
                        'guest_team_short' => 'BVB',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=618',
                        'color_code' => 'red',
                        'c_heading' => 'BMG vs. BVB 4 - 9',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    7 =>
                    array(
                        'id' => '619',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '12',
                        'gast_verein' => '8',
                        'datum' => '1593453600',
                        'home_tore' => '2',
                        'gast_tore' => '2',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Eintracht Frankfurt',
                        'home_team_short' => 'SGE',
                        'guest_team_name' => 'VfL Wolfsburg',
                        'guest_team_short' => 'VfL',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=619',
                        'color_code' => 'red',
                        'c_heading' => 'SGE vs. VfL 2 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    8 =>
                    array(
                        'id' => '620',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '7',
                        'gast_verein' => '14',
                        'datum' => '1593453600',
                        'home_tore' => '3',
                        'gast_tore' => '3',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Bayer Leverkusen',
                        'home_team_short' => 'BAY',
                        'guest_team_name' => 'Mainz 05',
                        'guest_team_short' => 'M05',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=620',
                        'color_code' => 'red',
                        'c_heading' => 'BAY vs. M05 3 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    9 =>
                    array(
                        'id' => '621',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '10',
                        'gast_verein' => '13',
                        'datum' => '1593453600',
                        'home_tore' => '1',
                        'gast_tore' => '1',
                        'time' => '1593453600',
                        'date' => '2020-06-29',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'FC Union Berlin',
                        'home_team_short' => 'FCU',
                        'guest_team_name' => 'Hertha BSC Berlin',
                        'guest_team_short' => 'BSC',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=621',
                        'color_code' => 'red',
                        'c_heading' => 'FCU vs. BSC 1 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            1 =>
            array(
                'date' => '2020-06-30',
                'day' => 30,
                'day_of_week' => 'TUE',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '90',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593522000',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1593522000',
                        'date' => '2020-06-30',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=90',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '919',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '33',
                        'gast_verein' => '36',
                        'datum' => '1593540000',
                        'home_tore' => '1',
                        'gast_tore' => '0',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'RB Leipzig',
                        'home_team_short' => 'RBL',
                        'guest_team_name' => 'SV Waldhof Mannheim',
                        'guest_team_short' => 'SVWM',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=919',
                        'color_code' => 'red',
                        'c_heading' => 'RBL vs. SVWM 1 - 0',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    2 =>
                    array(
                        'id' => '920',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '27',
                        'gast_verein' => '24',
                        'datum' => '1593540000',
                        'home_tore' => '4',
                        'gast_tore' => '4',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Hannover 96',
                        'home_team_short' => 'H96',
                        'guest_team_name' => '1. FC Kaiserslautern',
                        'guest_team_short' => 'FCK',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=920',
                        'color_code' => 'red',
                        'c_heading' => 'H96 vs. FCK 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    3 =>
                    array(
                        'id' => '921',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '25',
                        'gast_verein' => '31',
                        'datum' => '1593540000',
                        'home_tore' => '4',
                        'gast_tore' => '0',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => '1. FC Nürnberg',
                        'home_team_short' => 'FCN',
                        'guest_team_name' => 'Karlsruher SC',
                        'guest_team_short' => 'KSC',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=921',
                        'color_code' => 'red',
                        'c_heading' => 'FCN vs. KSC 4 - 0',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    4 =>
                    array(
                        'id' => '922',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '28',
                        'gast_verein' => '34',
                        'datum' => '1593540000',
                        'home_tore' => '4',
                        'gast_tore' => '6',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Hansa Rostock',
                        'home_team_short' => 'HRS',
                        'guest_team_name' => 'VfB Stuttgart',
                        'guest_team_short' => 'VfB',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=922',
                        'color_code' => 'red',
                        'c_heading' => 'HRS vs. VfB 4 - 6',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    5 =>
                    array(
                        'id' => '923',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '35',
                        'gast_verein' => '32',
                        'datum' => '1593540000',
                        'home_tore' => '2',
                        'gast_tore' => '2',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'VfL Bochum',
                        'home_team_short' => 'VfLB',
                        'guest_team_name' => 'MSV Duisburg',
                        'guest_team_short' => 'MSVD',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=923',
                        'color_code' => 'red',
                        'c_heading' => 'VfLB vs. MSVD 2 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    6 =>
                    array(
                        'id' => '924',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '26',
                        'gast_verein' => '23',
                        'datum' => '1593540000',
                        'home_tore' => '5',
                        'gast_tore' => '3',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'FC St. Pauli',
                        'home_team_short' => 'STP',
                        'guest_team_name' => 'FC Ingolstadt 04',
                        'guest_team_short' => 'FCI',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=924',
                        'color_code' => 'red',
                        'c_heading' => 'STP vs. FCI 5 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    7 =>
                    array(
                        'id' => '925',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '21',
                        'gast_verein' => '19',
                        'datum' => '1593540000',
                        'home_tore' => '4',
                        'gast_tore' => '5',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Dynamo Dresden',
                        'home_team_short' => 'SGD',
                        'guest_team_name' => 'Arminia Bielefeld',
                        'guest_team_short' => 'ARM',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=925',
                        'color_code' => 'red',
                        'c_heading' => 'SGD vs. ARM 4 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    8 =>
                    array(
                        'id' => '926',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '30',
                        'gast_verein' => '22',
                        'datum' => '1593540000',
                        'home_tore' => '0',
                        'gast_tore' => '4',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'SSV Jahn Regensburg ',
                        'home_team_short' => 'JAHN',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=926',
                        'color_code' => 'red',
                        'c_heading' => 'JAHN vs. FCH 0 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    9 =>
                    array(
                        'id' => '927',
                        'spieltyp' => 'Ligaspiel',
                        'home_verein' => '20',
                        'gast_verein' => '29',
                        'datum' => '1593540000',
                        'home_tore' => '2',
                        'gast_tore' => '4',
                        'time' => '1593540000',
                        'date' => '2020-06-30',
                        'c_start_time' => '18:00',
                        'home_team_name' => 'Eintracht Braunschweig',
                        'home_team_short' => 'BTSV',
                        'guest_team_name' => 'Holstein Kiel',
                        'guest_team_short' => 'KSVH',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=927',
                        'color_code' => 'red',
                        'c_heading' => 'BTSV vs. KSVH 2 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            2 =>
            array(
                'date' => '2020-07-01',
                'day' => 1,
                'day_of_week' => 'WED',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '92',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593608400',
                        'home_goals' => '2',
                        'guest_goals' => '5',
                        'time' => '1593608400',
                        'date' => '2020-07-01',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=92',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            3 =>
            array(
                'date' => '2020-07-02',
                'day' => 2,
                'day_of_week' => 'THU',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '93',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593694800',
                        'home_goals' => '4',
                        'guest_goals' => '13',
                        'time' => '1593694800',
                        'date' => '2020-07-02',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=93',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 13',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '94',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '24',
                        'guest_team_id' => '1',
                        'matchdate' => '1593694800',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1593694800',
                        'date' => '2020-07-02',
                        'c_start_time' => '13:00',
                        'home_team_name' => '1. FC Kaiserslautern',
                        'home_team_short' => 'FCK',
                        'guest_team_name' => 'Borussia Dortmund',
                        'guest_team_short' => 'BVB',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=94',
                        'color_code' => 'gray',
                        'c_heading' => 'FCK vs. BVB 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    2 =>
                    array(
                        'id' => '970',
                        'spieltyp' => 'Freundschaft',
                        'home_verein' => '1',
                        'gast_verein' => '21',
                        'datum' => '1593716400',
                        'home_tore' => '9',
                        'gast_tore' => '2',
                        'time' => '1593716400',
                        'date' => '2020-07-02',
                        'c_start_time' => '19:00',
                        'home_team_name' => 'Borussia Dortmund',
                        'home_team_short' => 'BVB',
                        'guest_team_name' => 'Dynamo Dresden',
                        'guest_team_short' => 'SGD',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=970',
                        'color_code' => 'green',
                        'c_heading' => 'BVB vs. SGD 9 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            4 =>
            array(
                'date' => '2020-07-03',
                'day' => 3,
                'day_of_week' => 'FRI',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '96',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '1',
                        'guest_team_id' => '24',
                        'matchdate' => '1593781200',
                        'home_goals' => '3',
                        'guest_goals' => '7',
                        'time' => '1593781200',
                        'date' => '2020-07-03',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'Borussia Dortmund',
                        'home_team_short' => 'BVB',
                        'guest_team_name' => '1. FC Kaiserslautern',
                        'guest_team_short' => 'FCK',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=96',
                        'color_code' => 'gray',
                        'c_heading' => 'BVB vs. FCK 3 - 7',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '98',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593781200',
                        'home_goals' => '7',
                        'guest_goals' => '4',
                        'time' => '1593781200',
                        'date' => '2020-07-03',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=98',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 7 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            5 =>
            array(
                'date' => '2020-07-04',
                'day' => 4,
                'day_of_week' => 'SAT',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '95',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '24',
                        'guest_team_id' => '1',
                        'matchdate' => '1593867600',
                        'home_goals' => '2',
                        'guest_goals' => '1',
                        'time' => '1593867600',
                        'date' => '2020-07-04',
                        'c_start_time' => '13:00',
                        'home_team_name' => '1. FC Kaiserslautern',
                        'home_team_short' => 'FCK',
                        'guest_team_name' => 'Borussia Dortmund',
                        'guest_team_short' => 'BVB',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=95',
                        'color_code' => 'gray',
                        'c_heading' => 'FCK vs. BVB 2 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '99',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1593867600',
                        'home_goals' => '4',
                        'guest_goals' => '1',
                        'time' => '1593867600',
                        'date' => '2020-07-04',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=99',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            6 =>
            array(
                'date' => '2020-07-05',
                'day' => 5,
                'day_of_week' => 'SUN',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '97',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '1',
                        'guest_team_id' => '24',
                        'matchdate' => '1593954000',
                        'home_goals' => '4',
                        'guest_goals' => '4',
                        'time' => '1593954000',
                        'date' => '2020-07-05',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'Borussia Dortmund',
                        'home_team_short' => 'BVB',
                        'guest_team_name' => '1. FC Kaiserslautern',
                        'guest_team_short' => 'FCK',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=97',
                        'color_code' => 'gray',
                        'c_heading' => 'BVB vs. FCK 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
        ),
        1 =>
        array(
            0 =>
            array(
                'date' => '2020-07-06',
                'day' => 6,
                'day_of_week' => 'MON',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '100',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594040400',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1594040400',
                        'date' => '2020-07-06',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=100',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            1 =>
            array(
                'date' => '2020-07-07',
                'day' => 7,
                'day_of_week' => 'TUE',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '101',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594126800',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1594126800',
                        'date' => '2020-07-07',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=101',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '102',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '24',
                        'guest_team_id' => '1',
                        'matchdate' => '1594126800',
                        'home_goals' => '5',
                        'guest_goals' => '5',
                        'time' => '1594126800',
                        'date' => '2020-07-07',
                        'c_start_time' => '13:00',
                        'home_team_name' => '1. FC Kaiserslautern',
                        'home_team_short' => 'FCK',
                        'guest_team_name' => 'Borussia Dortmund',
                        'guest_team_short' => 'BVB',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=102',
                        'color_code' => 'gray',
                        'c_heading' => 'FCK vs. BVB 5 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            2 =>
            array(
                'date' => '2020-07-08',
                'day' => 8,
                'day_of_week' => 'WED',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '103',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '24',
                        'guest_team_id' => '1',
                        'matchdate' => '1594213200',
                        'home_goals' => '4',
                        'guest_goals' => '2',
                        'time' => '1594213200',
                        'date' => '2020-07-08',
                        'c_start_time' => '13:00',
                        'home_team_name' => '1. FC Kaiserslautern',
                        'home_team_short' => 'FCK',
                        'guest_team_name' => 'Borussia Dortmund',
                        'guest_team_short' => 'BVB',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=103',
                        'color_code' => 'gray',
                        'c_heading' => 'FCK vs. BVB 4 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '104',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594213200',
                        'home_goals' => '2',
                        'guest_goals' => '2',
                        'time' => '1594213200',
                        'date' => '2020-07-08',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=104',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            3 =>
            array(
                'date' => '2020-07-09',
                'day' => 9,
                'day_of_week' => 'THU',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '105',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594299600',
                        'home_goals' => '4',
                        'guest_goals' => '4',
                        'time' => '1594299600',
                        'date' => '2020-07-09',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=105',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            4 =>
            array(
                'date' => '2020-07-10',
                'day' => 10,
                'day_of_week' => 'FRI',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '106',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594386000',
                        'home_goals' => '3',
                        'guest_goals' => '2',
                        'time' => '1594386000',
                        'date' => '2020-07-10',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=106',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 3 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    1 =>
                    array(
                        'id' => '107',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '1',
                        'guest_team_id' => '24',
                        'matchdate' => '1594386000',
                        'home_goals' => '0',
                        'guest_goals' => '2',
                        'time' => '1594386000',
                        'date' => '2020-07-10',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'Borussia Dortmund',
                        'home_team_short' => 'BVB',
                        'guest_team_name' => '1. FC Kaiserslautern',
                        'guest_team_short' => 'FCK',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=107',
                        'color_code' => 'gray',
                        'c_heading' => 'BVB vs. FCK 0 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                    2 =>
                    array(
                        'id' => '971',
                        'spieltyp' => 'Freundschaft',
                        'home_verein' => '1',
                        'gast_verein' => '21',
                        'datum' => '1594407600',
                        'home_tore' => '7',
                        'gast_tore' => '0',
                        'time' => '1594407600',
                        'date' => '2020-07-10',
                        'c_start_time' => '19:00',
                        'home_team_name' => 'Borussia Dortmund',
                        'home_team_short' => 'BVB',
                        'guest_team_name' => 'Dynamo Dresden',
                        'guest_team_short' => 'SGD',
                        'table' => '_spiel',
                        'link' => '/?page=match&id=971',
                        'color_code' => 'green',
                        'c_heading' => 'BVB vs. SGD 7 - 0',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            5 =>
            array(
                'date' => '2020-07-11',
                'day' => 11,
                'day_of_week' => 'SAT',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '108',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594472400',
                        'home_goals' => '4',
                        'guest_goals' => '2',
                        'time' => '1594472400',
                        'date' => '2020-07-11',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=108',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            6 =>
            array(
                'date' => '2020-07-12',
                'day' => 12,
                'day_of_week' => 'SUN',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '109',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594558800',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1594558800',
                        'date' => '2020-07-12',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=109',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
        ),
        2 =>
        array(
            0 =>
            array(
                'date' => '2020-07-13',
                'day' => 13,
                'day_of_week' => 'MON',
                'appointments' =>
                array(),
            ),
            1 =>
            array(
                'date' => '2020-07-14',
                'day' => 14,
                'day_of_week' => 'TUE',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '110',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594731600',
                        'home_goals' => '3',
                        'guest_goals' => '4',
                        'time' => '1594731600',
                        'date' => '2020-07-14',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=110',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 3 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            2 =>
            array(
                'date' => '2020-07-15',
                'day' => 15,
                'day_of_week' => 'WED',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '111',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594818000',
                        'home_goals' => '5',
                        'guest_goals' => '4',
                        'time' => '1594818000',
                        'date' => '2020-07-15',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=111',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 5 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            3 =>
            array(
                'date' => '2020-07-16',
                'day' => 16,
                'day_of_week' => 'THU',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '112',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594904400',
                        'home_goals' => '4',
                        'guest_goals' => '5',
                        'time' => '1594904400',
                        'date' => '2020-07-16',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=112',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            4 =>
            array(
                'date' => '2020-07-17',
                'day' => 17,
                'day_of_week' => 'FRI',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '113',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1594990800',
                        'home_goals' => '6',
                        'guest_goals' => '6',
                        'time' => '1594990800',
                        'date' => '2020-07-17',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=113',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 6 - 6',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            5 =>
            array(
                'date' => '2020-07-18',
                'day' => 18,
                'day_of_week' => 'SAT',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '114',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595077200',
                        'home_goals' => '6',
                        'guest_goals' => '3',
                        'time' => '1595077200',
                        'date' => '2020-07-18',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=114',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 6 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            6 =>
            array(
                'date' => '2020-07-19',
                'day' => 19,
                'day_of_week' => 'SUN',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '115',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595163600',
                        'home_goals' => '0',
                        'guest_goals' => '3',
                        'time' => '1595163600',
                        'date' => '2020-07-19',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=115',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 0 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
        ),
        3 =>
        array(
            0 =>
            array(
                'date' => '2020-07-20',
                'day' => 20,
                'day_of_week' => 'MON',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '116',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595250000',
                        'home_goals' => '4',
                        'guest_goals' => '5',
                        'time' => '1595250000',
                        'date' => '2020-07-20',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=116',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            1 =>
            array(
                'date' => '2020-07-21',
                'day' => 21,
                'day_of_week' => 'TUE',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '117',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595336400',
                        'home_goals' => '4',
                        'guest_goals' => '3',
                        'time' => '1595336400',
                        'date' => '2020-07-21',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=117',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            2 =>
            array(
                'date' => '2020-07-22',
                'day' => 22,
                'day_of_week' => 'WED',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '118',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595422800',
                        'home_goals' => '2',
                        'guest_goals' => '2',
                        'time' => '1595422800',
                        'date' => '2020-07-22',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=118',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 2',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            3 =>
            array(
                'date' => '2020-07-23',
                'day' => 23,
                'day_of_week' => 'THU',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '119',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595509200',
                        'home_goals' => '4',
                        'guest_goals' => '3',
                        'time' => '1595509200',
                        'date' => '2020-07-23',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=119',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            4 =>
            array(
                'date' => '2020-07-24',
                'day' => 24,
                'day_of_week' => 'FRI',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '120',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595595600',
                        'home_goals' => '3',
                        'guest_goals' => '1',
                        'time' => '1595595600',
                        'date' => '2020-07-24',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=120',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 3 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            5 =>
            array(
                'date' => '2020-07-25',
                'day' => 25,
                'day_of_week' => 'SAT',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '121',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595682000',
                        'home_goals' => '5',
                        'guest_goals' => '3',
                        'time' => '1595682000',
                        'date' => '2020-07-25',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=121',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 5 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            6 =>
            array(
                'date' => '2020-07-26',
                'day' => 26,
                'day_of_week' => 'SUN',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '122',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595768400',
                        'home_goals' => '4',
                        'guest_goals' => '4',
                        'time' => '1595768400',
                        'date' => '2020-07-26',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=122',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
        ),
        4 =>
        array(
            0 =>
            array(
                'date' => '2020-07-27',
                'day' => 27,
                'day_of_week' => 'MON',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '123',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595854800',
                        'home_goals' => '4',
                        'guest_goals' => '4',
                        'time' => '1595854800',
                        'date' => '2020-07-27',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=123',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            1 =>
            array(
                'date' => '2020-07-28',
                'day' => 28,
                'day_of_week' => 'TUE',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '124',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1595941200',
                        'home_goals' => '3',
                        'guest_goals' => '3',
                        'time' => '1595941200',
                        'date' => '2020-07-28',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=124',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 3 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            2 =>
            array(
                'date' => '2020-07-29',
                'day' => 29,
                'day_of_week' => 'WED',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '125',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1596027600',
                        'home_goals' => '2',
                        'guest_goals' => '3',
                        'time' => '1596027600',
                        'date' => '2020-07-29',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=125',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 3',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            3 =>
            array(
                'date' => '2020-07-30',
                'day' => 30,
                'day_of_week' => 'THU',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '126',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1596114000',
                        'home_goals' => '8',
                        'guest_goals' => '5',
                        'time' => '1596114000',
                        'date' => '2020-07-30',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=126',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 8 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            4 =>
            array(
                'date' => '2020-07-31',
                'day' => 31,
                'day_of_week' => 'FRI',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '127',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1596200400',
                        'home_goals' => '4',
                        'guest_goals' => '4',
                        'time' => '1596200400',
                        'date' => '2020-07-31',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=127',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 4 - 4',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            5 =>
            array(
                'date' => '2020-08-01',
                'day' => 1,
                'day_of_week' => 'SAT',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '128',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1596286800',
                        'home_goals' => '5',
                        'guest_goals' => '5',
                        'time' => '1596286800',
                        'date' => '2020-08-01',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=128',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 5 - 5',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
            6 =>
            array(
                'date' => '2020-08-02',
                'day' => 2,
                'day_of_week' => 'SUN',
                'appointments' =>
                array(
                    0 =>
                    array(
                        'id' => '129',
                        'spieltyp' => 'Freundschaft',
                        'home_team_id' => '6',
                        'guest_team_id' => '22',
                        'matchdate' => '1596373200',
                        'home_goals' => '2',
                        'guest_goals' => '1',
                        'time' => '1596373200',
                        'date' => '2020-08-02',
                        'c_start_time' => '13:00',
                        'home_team_name' => 'SC Freiburg',
                        'home_team_short' => 'SCF',
                        'guest_team_name' => '1. FC Heidenheim 1846 ',
                        'guest_team_short' => 'FCH',
                        'table' => '_youthmatch',
                        'link' => '/?page=youth-match&id=129',
                        'color_code' => 'gray',
                        'c_heading' => 'SCF vs. FCH 2 - 1',
                        'user_type' => 'admin',
                        'is_match' => 1,
                    ),
                ),
            ),
        ),
    ),
);